export { default as FlagEn } from './flag_en.svg'
export { default as FlagVi } from './flag_vi.svg'
export { default as LogoIcon } from './logo.svg'
export { default as SearchIcon } from './search.svg'
export { default as NotificationIcon } from './notification.svg'
export { default as ExploreIcon } from './explore.svg'
export { default as MoreIcon } from './more.svg'
export { default as AddListIcon } from './add_list.svg'
export { default as DownloadIcon } from './download.svg'
export { default as ReportIcon } from './report.svg'
export { default as ShareIcon } from './share.svg'
export { default as StopIcon } from './stop.svg'
export { default as HomeIcon } from './home.svg'
export { default as HeartIcon } from './heart.svg'
export { default as LiveIcon } from './live.svg'
export { default as UserIcon } from './user.svg'
export { default as LotusIcon } from './lotus.svg'
export { default as LeftArrowIcon } from './left_arrow.svg'
export { default as PlayIcon } from './play.svg'
export { default as PlaySmall } from './play_small.svg'
export { default as PauseIcon } from './pause.svg'
import DownArrow from './down_arrow.svg'
export { default as FullscreenIcon } from './full_screen.svg'
export { default as SmallScreenIcon } from './small_screen.svg'
export { default as LoadingIcon } from './loading.svg'
export { default as SpeedArrowIcon } from './speed_arrow.svg'
export { default as ChevronDownIcon } from './chevron_down.svg'
export { default as MessageIcon } from './message_box.svg'
export { default as LockedIcon } from './locked.svg'
export { default as UnlockedIcon } from './unlocked.svg'
export { default as VolumeIcon } from './volume.svg'
export { default as FastBackwardIcon } from './fast_backward.svg'
export { default as FastForwardIcon } from './fast_forward.svg'
export { default as Volume1Icon } from './volume_1.svg'
export { default as Volume2Icon } from './volume_2.svg'
export { default as Volume3Icon } from './volume_3.svg'
export { default as MuteIcon } from './mute.svg'
export { default as AddIcon } from './+.svg'
export { default as AddPrimaryIcon } from './+Primary.svg'
export { default as SortListIcon } from './sort_list.svg'
export { default as EmojiIcon } from './emoji.svg'
export { default as SendIcon } from './send.svg'
export { default as SettingIcon } from './settings.svg'
export { default as SettingFillIcon } from './setting-fill.svg'
export { default as PlaybackSpeedIcon } from './playback_speed.svg'
export { default as ClockIcon } from './clock.svg'
export { default as DeleteIcon } from './delete_icon.svg'
export { default as EditPen } from './edit_pen.svg'
export { default as ShareLinkIcon } from './shareLink.svg'
export { default as MessageFacebookIcon } from './messenger.svg'
export { default as TwitterIcon } from './twitter.svg'
export { default as GoogleIcon } from './google.svg'
export { default as TelegramIcon } from './telegram.svg'
export { default as SquareIcon } from './square.svg'
export { default as SquareEmptyIcon } from './square_empty.svg'
export { default as CheckIcon } from './check.svg'
export { default as ShareFillIcon } from './share_fill.svg'
export { default as RefreshIcon } from './refresh.svg'
export { default as FacebookIcon } from './facebook.svg'
export { default as DirectionsIcon } from './directions.svg'
export { default as WatchLaterFillIcon } from './watch-later.svg'
import AvatarIcon from './default_avatar.jpg'
import CommentIcon from './comment.svg'
import CloseIcon from './close.svg'
import LogoAdvertisementLogo from './logo_adventisement.svg'
import ViewIcon from './view.svg'
export { default as HeartFilled } from './heart_filled.svg'
export { default as ActiveHome } from './home_filled.svg'
export { default as RadioChecked } from './radio_checked.svg'
export { default as RadioEmpty } from './radio_empty.svg'
export { default as PhimIcon } from './phim.svg'
export { default as DefaultAvavar } from './defaultAvatar.svg'
export { default as DollarIcon } from './dollar.svg'
export { default as CashIcon } from './cash.svg'
export { default as CrownIcon } from './crown.svg'
export { default as CameraOnIcon } from './camera_on.svg'
export { default as HeartMenuIcon } from './heart_menu.svg'
export { default as UserCheckedIcon } from './user_check.svg'
export { default as RecentIcon } from './recent_clock.svg'
export { default as WatchLaterIcon } from './watch_later_clock.svg'
export { default as ListMenuIcon } from './list_menu.svg'
export { default as LinkIcon } from './link.svg'
export { default as LockedMenuIcon } from './locked_menu.svg'
export { default as DocumentIcon } from './document.svg'
export { default as ShieldIcon } from './shield.svg'
export { default as BookIcon } from './book.svg'
export { default as ContactIcon } from './contact.svg'
export { default as LogoutIcon } from './log_out.svg'
export { default as ZaloIcon } from './zalo.svg'
export { default as HeartFilledColor } from './heartfill.svg'

import GooglePlay from './Google Play.png'
import AppStore from './App Store.png'
import BoCongThuong from './BoCongThuong.png'
export {
  AvatarIcon,
  DownArrow,
  CommentIcon,
  CloseIcon,
  LogoAdvertisementLogo,
  ViewIcon,
  GooglePlay,
  AppStore,
  BoCongThuong,
}
